title: FIRST BLOG
author: GURKARANPREET SINGH 
email: gpreetsinghdhillon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  IT student aispiring to become front end developer.

# social links
twitter_username: GurkaranpreetS6 # DO NOT include the @ character, or else the build will fail!
github_username:  gurkaran321 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima
